services:
  legacy-api:
    command: ./bin/start_web_server.sh
    # command: "bash -c \"while [ true ]; do echo 'hi'; sleep 5; done\""
    port: 3088
    internal: true
    environment:
      - PORT=3088

      # ruby garbage collection fixes
        # default none
      - MALLOC_ARENA_MAX=3
        # default 4096   Must be > 0
      - RUBY_GC_HEAP_FREE_SLOTS=4096
        # default 10000  Must be > 0
      - RUBY_GC_HEAP_INIT_SLOTS=10000
        # default 1.8   Must be > 1.0
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.2
        # default 0 (disabled);Must be > 0
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=3096
        # default 2.0   Must be > 0
      - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.2
        # default 16777216  Must be > 0
      - RUBY_GC_MALLOC_LIMIT=8500000
        # default 33554432   Must be > 0
      - RUBY_GC_MALLOC_LIMIT_MAX=15000000
        # default 1.4   Must be > 1.0
      - RUBY_GC_MALLOC_LIMIT_GROWTH_FACTOR=1.2

      # shared ENV variables
      - WB_ENV
      - GEMFURY_SECRET
      - WB_DIETBET_LOG_LEVEL
      - REDIS_HOST
      - STEPBET_LEGACY_MAX_HTTP_THREADS
      - STEPBET_LEGACY_DB
      - STEPBET_LEGACY_DB_HOST
      - STEPBET_LEGACY_DB_PORT
      - STEPBET_LEGACY_DB_USERNAME
      - STEPBET_LEGACY_DB_PASSWORD
      - DIETBET_LEGACY_MAX_HTTP_THREADS
      - DIETBET_LEGACY_DB
      - DIETBET_LEGACY_DB_HOST
      - DIETBET_LEGACY_DB_PORT
      - DIETBET_LEGACY_DB_USERNAME
      - DIETBET_LEGACY_DB_PASSWORD
    health:
      path: /ping/lb
      interval: 60
      timeout: 3
timers:
  updateStats:
    schedule: "*/6 * * * ?"
    command: "./bin/rails runner Stats::Dietbet.update_all"
    service: legacy-api
