environment:
  - GEN2=true
services:
  web:
    domain: web.dietbet-game-service.convox
    command: "/usr/local/bin/apache2-foreground"
    port: 80
    health:
      interval: 30
      path: /api/game-service/ping/lb
    environment:
      - PORT=80
      - DIETBET_GAME_SERVICE_USE_ENV_VARS=true
      - DIETBET_DB_HOST
      - DIETBET_DB_PORT
      - DIETBET_DB_USERNAME
      - DIETBET_DB_PASSWORD
      - STEPBET_DB_HOST
      - STEPBET_DB_PORT
      - STEPBET_DB_USERNAME
      - STEPBET_DB_PASSWORD
      - WB_USER_DB_HOST
      - WB_USER_DB_PASSWORD
      - WB_USER_DB_PORT
      - WB_USER_DB_USERNAME
      - API_CLIENT_JWT_SECRET
      - WB_AUTH_SERVICE_EXTERNAL_URL
      - WB_BILLING_SERVICE_REST_API_HOST
      - WB_GRAPHQL_SERVICE_EXTERNAL_URL
      - WB_AUTH_SERVICE_SESSION_COOKIE
      - WB_CSRF_COOKIE
      - DIETBET_SMTP_SERVER
      - DIETBET_SMTP_PORT
      - DIETBET_SMTP_USERNAME
      - DIETBET_SMTP_PASSWORD
      - DIETBET_FACEBOOK_APP_ID
      - DIETBET_FACEBOOK_APP_URL
      - DIETBET_CLOUDSPONGE_DOMAIN_KEY
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PRIVATE_KEY
      - BRAINTREE_PUBLIC_KEY
      - DIETBET_IMAGE_SERVER_URL
      - STEPBET_IMAGE_SERVER_URL
      - STEPBET_SITE_URL
      - DIETBET_DAILY_BURN_OAUTH_ACCESS_TOKEN
      - DIETBET_GOOGLE_ANALYTICS_IPHONE_ACCOUNT
      - DIETBET_GOOGLE_ANALYTICS_ANDROID_ACCOUNT
      - DIEBET_GOOGLE_RECAPTCHA_SITE_KEY
      - DIEBET_GOOGLE_RECAPTCHA_SECRET
      - DIEBET_MOLLOM_PUBLIC_KEY
      - DIEBET_MOLLOM_PRIVATE_KEY
      - BRAINTREE_OAUTH_CLIENT_ID
      - BRAINTREE_OAUTH_CLIENT_ID