---
environment:
  ####################
  #                  #
  # General Settings #
  #                  #
  ####################
  - ALLOW_UNCONFIGURED_SERVICES=false
  - INIT_AND_SEED=false
  - PUBSUB_CHANNEL_CLIENT_ALERTS=pub_sub_channel_client_alerts
  - PUBSUB_CHANNEL_UPDATE_CLIENT_RUNS=pub_sub_channel_update_client_runs
  - QUEUE_NAME_REQUEST_GAME_SERVICE_RUNS_UPDATE=game_service_run_update_requests
  - RUNBET_RUN_INTERVAL
  - SKIP_SIMPLECOV=true
  - WAIT_FOR_REDIS=true
  - WB_ENV
  - WB_INTERNAL_URL_SCHEME=https
  - VERIFY_CERTS=false
  - API_CLIENT_JWT_SECRET
  - REDIS_HOST
  - GEN2=true
  - DISABLE_SPRING=1
  ###########################
  #                         #
  # Service to Service URLs #
  #                         #
  ###########################
  - WB_METRIC_SERVICE_HOST
  - WB_NOTIFY_SERVICE_HOST
  - WB_SOCIAL_SERVICE_HOST
  - WB_BILLING_SERVICE_HOST
  - WB_USER_SERVICE_HOST
  #####################
  #                   #
  # Database Settings #
  #                   #
  #####################
  - RUNBET_GAME_SERVICE_DB_HOST
  - RUNBET_GAME_SERVICE_DB_PASSWORD
  - RUNBET_GAME_SERVICE_DB_PORT
  - RUNBET_GAME_SERVICE_DB_USERNAME
  - RUNBET_GAME_SERVICE_MAX_HTTP_THREADS
  #############################
  #                           #
  # wb-game Database Settings #
  #                           #
  #############################
  - WB_GAME_DB_HOST=
  - WB_GAME_DB_PASSWORD=
  - WB_GAME_DB_PORT=
  - WB_GAME_DB_USERNAME=
  ################
  #              #
  # Gem Settings #
  #              #
  ################
  - GEMFURY_SECRET
  - WB_GAME_GEM_PATH=
  - WB_MESSAGING_GEM_PATH=
  - WB_SERVICE_GEM_PATH=
  - WEBSPRAY_GEM_PATH=
  - RACK_JWT_GEM_PATH=
  #############
  #           #
  # Profiling #
  #           #
  #############
  - DATADOG_APM_ENABLED=false
  - DD_APM_IGNORE_RESOURCES=
  - RUNBET_PROFILE_REQUESTS=false
  - RUNBET_PROF_OUT=
  ####################
  #                  #
  # Ruby GC settings #
  #                  #
  ####################
  - MALLOC_ARENA_MAX=3  # default: none
  - RUBY_GC_HEAP_FREE_SLOTS=4096  # default 4096   Must be > 0
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.2  # default 1.8   Must be > 1.0
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=3096  # default 0 (disabled);Must be > 0
  - RUBY_GC_HEAP_INIT_SLOTS=10000  # default 10000  Must be > 0
  - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.2  # default 2.0   Must be > 0
  - RUBY_GC_MALLOC_LIMIT=8500000  # default 16777216  Must be > 0
  - RUBY_GC_MALLOC_LIMIT_GROWTH_FACTOR=1.2  # default 1.4   Must be > 1.0
  - RUBY_GC_MALLOC_LIMIT_MAX=15000000  # default 33554432   Must be > 0
services:
  engine:
    # command: "bash -c \"while [ true ]; do echo 'hi'; sleep 5; done\""
    command: ./bin/start_daemon.sh
    scale:
      memory: 512
    internal: true
  web:
    # command: "bash -c \"while [ true ]; do echo 'hi'; sleep 5; done\""
    command: ./bin/start_web_server.sh
    health:
      path: /ping/lb
      interval: 60
      timeout: 3
    scale:
      memory: 1024
    port: 3004
    internal: true
    environment:
      - PORT=3004
  messaging:
    # command: "bash -c \"while [ true ]; do echo 'hi'; sleep 5; done\""
    command: ./bin/start_message_api_daemon.sh
    scale:
      memory: 512
    internal: true
