environment:
  - GEN2=true
  - NPM_CONFIG_REGISTRY
services:
  web:
    domain: ${WB_ADMIN_WEB_DOMAIN}
    command: bash -c 'wget https://dev.dietbet.com/files/convox/ninja-selfsigned-rootCA.crt -O "/usr/share/ca-certificates/ninja-selfsigned-rootCA.crt" && export NODE_EXTRA_CA_CERTS="/usr/share/ca-certificates/ninja-selfsigned-rootCA.crt" && echo "ninja-selfsigned-rootCA.crt" >> "/etc/ca-certificates.conf" && cat "/usr/share/ca-certificates/ninja-selfsigned-rootCA.crt" && wget https://dev.dietbet.com/files/convox/office-selfsigned-rootCA.crt -O "/usr/share/ca-certificates/office-selfsigned-rootCA.crt" && export NODE_EXTRA_CA_CERTS="/usr/share/ca-certificates/office-selfsigned-rootCA.crt" && echo "office-selfsigned-rootCA.crt" >> "/etc/ca-certificates.conf" && cat "/usr/share/ca-certificates/office-selfsigned-rootCA.crt" && update-ca-certificates && npm start'
    port: 8010
    scale:
      memory: 512
    health:
      path: /ping/lb
      interval: 30
    environment:
      - PORT=8010
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_UPLOAD_RUNBET_GAME_PRESET
      - CLOUDINARY_UPLOAD_FALKOR_GAME_PRESET
      - CLOUDINARY_UPLOAD_FALKOR_METRIC_PRESET
      - CLOUDINARY_UPLOAD_FALKOR_SOCIAL_PRESET
      - CLOUDINARY_UPLOAD_URL
      - NODE_ENV
      - WB_ADMIN_AUTH_PROVIDER
      - WB_ADMIN_AUTH_SERVICE_BASE_URL
      - WB_ADMIN_WEB_LOG_LEVEL
      - WB_ADMIN_GRAPHQL_SERVICE_EXTERNAL_URL
      - WB_GRAPHQL_SERVICE_SHIFT_PORT
      - WB_ENFORCE_HTTPS
      - WB_ENV
      - WB_STEPBET_ADMIN_URL
      - WB_DIETBET_ADMIN_URL
