environment:
  - GEN2=true
  - NPM_CONFIG_REGISTRY
services:
  web:
    domain: ${WB_AUTH_SERVICE_DOMAIN}
    command: bash -c 'wget https://dev.dietbet.com/files/convox/office-dev-convox-local-rack.crt -O "/usr/share/ca-certificates/convox.crt" && echo "convox.crt" >> "/etc/ca-certificates.conf" && update-ca-certificates && cat "/usr/share/ca-certificates/convox.crt" && export NODE_EXTRA_CA_CERTS="/usr/share/ca-certificates/convox.crt" && npm start'
    port: 8000
    scale:
      memory: 512
    health:
      path: /ping/lb
    environment:
      - PORT=8000
      - API_CLIENT_JWT_SECRET
      - APPLE_LOGIN_WEB_APPS
      - ACCOUNTS_APPLE_CLIENT_ID
      - ACCOUNTS_APPLE_CALLBACK_URL
      - DIETBET_FACEBOOK_CLIENT_ID
      - DIETBET_FACEBOOK_CLIENT_SECRET
      - FACEBOOK_CLIENT_ID
      - FACEBOOK_CLIENT_SECRET
      - FACEBOOK_LOGIN_APPS
      - FACEBOOK_PROFILE_URL
      - FITBIT_ACTIVITIES_SUBSCRIPTION_ID
      - FITBIT_ACTIVITIES_SUBSCRIBER_ID
      - FITBIT_CLIENT_ID
      - FITBIT_CLIENT_SECRET
      - FITBIT_MOBILE_CALLBACK_URL
      - GARMIN_CLIENT_ID
      - GARMIN_CLIENT_SECRET
      - GARMIN_MOBILE_CALLBACK_URL
      - GOOGLE_RECAPTCHA_V2_PRIVATE_KEY=set_me
      - GOOGLE_RECAPTCHA_V2_PUBLIC_KEY=set_me
      - HUB_APPLE_CLIENT_ID
      - HUB_APPLE_CALLBACK_URL
      - HUB_FACEBOOK_CLIENT_ID
      - HUB_FACEBOOK_CLIENT_SECRET
      - NODE_ENV
      - NPM_CONFIG_REGISTRY
      - REDIS_HOST
      - RUNBET_FACEBOOK_CLIENT_ID=_set_me_
      - RUNBET_FACEBOOK_CLIENT_SECRET=_set_me_
      - RUNKEEPER_CLIENT_ID
      - RUNKEEPER_CLIENT_SECRET
      - RUNKEEPER_MOBILE_CALLBACK_URL
      - SESSION_COOKIE_SECRET
      - STEPBET_FACEBOOK_CLIENT_ID
      - STEPBET_FACEBOOK_CLIENT_SECRET
      - STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET
      - STRAVA_MOBILE_CALLBACK_URL
      - WAYBETTER_APPLE_CLIENT_KEY
      - WAYBETTER_APPLE_CLIENT_ID
      - WAYBETTER_APPLE_CLIENT_SECRET
      - WAYBETTER_APPLE_CLIENT_TEAM_ID
      - WAYBETTER_FACEBOOK_CLIENT_ID
      - WAYBETTER_FACEBOOK_CLIENT_SECRET
      - WB_ALTERNATE_DOMAINS=''
      - WB_AUTH_SERVICE_CORS_WHITELIST
      - WB_AUTH_SERVICE_EXPIRE_AUTH_COOKIES_DAYS
      - WB_AUTH_SERVICE_EXTERNAL_URL
      - WB_AUTH_SERVICE_JWT_EXPIRES_IN
      - WB_AUTH_SERVICE_LOG_LEVEL
      - WB_AUTH_SERVICE_REDIS_SESSION_PREFIX_KEY
      - WB_AUTH_SERVICE_SESSION_COOKIE
      - WB_AUTH_SERVICE_SESSION_PROXY
      - WB_CSRF_COOKIE
      - WB_DOMAIN
      - WB_ENFORCE_HTTPS
      - WB_ENV
      - WB_EXTERNAL_URL_SCHEME
      - WB_HEALTH_CHECK_PASSWORD
      - WB_HEALTH_CHECK_USERNAME
      - WB_INTERNAL_URL_SCHEME
      - WB_JWT_COOKIE
      - WB_SECURE_COOKIES
      # user service convox G1 link
      - WB_USER_SERVICE_HOST
      - WB_USER_SERVICE_PORT
