environment:
  ##############################
  #
  #  Debug, dev
  #
  ##############################
  # eg.
  # convox env set A_GEM_PATH_VAR=/app/vendor/gems/dev/wb-service
  - BS_WB_MESSAGING_GEM_PATH=
  - BS_WB_SEARCH_GEM_PATH=
  - BS_WB_SERVICE_GEM_PATH=
  - BS_WB_RUBOCOP=
  - BS_WEBSPRAY=

  ##############################
  #
  #  HTTP Config
  #
  ##############################
  - PORT=3006
  - WB_BILLING_SERVICE_WEB_CONCURRENCY=1
  - WB_BILLING_SERVICE_MAX_THREADS=2

  ##############################
  #
  #  Daemon Config
  #
  ##############################
  - WB_BILLING_SERVICE_PAYOUT_DAEMON_IDLE_SLEEP_TIME=120
  - PAYMENT_METHOD_EXPIRATION_WARNING_PERIOD=604800
  - SUBSCRIPTION_CREDIT_TRIGGER_PERIOD=86400

  ##############################
  #
  #  Service linking, config
  #
  ##############################
  - GEN2=true
  - WB_ENV
  - WB_INTERNAL_URL_SCHEME=http
  - API_CLIENT_JWT_SECRET
  - REDIS_HOST
  - ALLOW_UNCONFIGURED_SERVICES=
  - VERIFY_CERTS=false

  - WB_NOTIFY_SERVICE_HOST
  - WB_NOTIFY_SERVICE_PORT=80
  - WB_USER_SERVICE_HOST
  - WB_USER_SERVICE_PORT=80
  - RUNBET_GAME_SERVICE_HOST
  - RUNBET_GAME_SERVICE_PORT=443
  - QUITBET_GAME_SERVICE_HOST
  - QUITBET_GAME_SERVICE_PORT=80
  - FALKOR_GAME_SERVICE_HOST
  - FALKOR_GAME_SERVICE_PORT=443
  - DIETBET_GAME_SERVICE_HOST
  - DIETBET_GAME_SERVICE_PORT=80
  - DIETBET_GAME_SERVICE_SCHEME=http
  - STEPBET_GAME_SERVICE_HOST
  - STEPBET_GAME_SERVICE_PORT=80
  - STEPBET_GAME_SERVICE_SCHEME=http
  - MEMBERSHIP_SERVICE_HOST
  - MEMBERSHIP_SERVICE_PORT=443
  - MEMBERSHIP_SERVICE_SCHEME=http
  - WB_BILLING_SERVICE_DB_HOST
  - WB_BILLING_SERVICE_DB_USERNAME
  - WB_BILLING_SERVICE_DB_PASSWORD
  - WB_BILLING_SERVICE_DB_INTERNAL_PORT=3306
  - WB_BILLING_SERVICE_DOMAIN

  ##############################
  #
  #  External services config
  #
  ##############################
  - GEMFURY_SECRET
  - BRAINTREE_ENVIRONMENT
  - BRAINTREE_MERCHANT_ID
  - BRAINTREE_PUBLIC_KEY
  - BRAINTREE_PRIVATE_KEY
  - PAYPAL_CLIENT_ID
  - PAYPAL_CLIENT_SECRET
  - CLOUDINARY_CLOUD_NAME
  - CLOUDINARY_UPLOAD_PRESET
  - CLOUDINARY_UPLOAD_URL
  - ITUNES_API_HOST
  - ITUNES_SANDBOX_API_HOST=http://localhost
  - ITUNES_SHARED_SECRET
  - APPLE_IAP_SUBSCRIPTION_GRACE_PERIOD_SECONDS=300
  - APPLE_IAP_SUBSCRIPTION_INSPECTION_WINDOW_DAYS=0.5

  ##############################
  #
  #  Pub sub, Qs
  #
  ##############################
  - QUEUE_NAME_REQUEST_METRIC_SERVICE_STEPS_UPDATE=metric_service_step_update_requests
  - QUEUE_NAME_REQUEST_GAME_SERVICE_STEPS_UPDATE=game_service_step_update_requests
  - QUEUE_NAME_REQUEST_METRIC_SERVICE_RUNS_UPDATE=metric_service_run_update_requests
  - QUEUE_NAME_REQUEST_GAME_SERVICE_RUNS_UPDATE=game_service_run_update_requests
  - PUBSUB_CHANNEL_UPDATE_CLIENT_STEPS=pub_sub_channel_update_client_steps
  - PUBSUB_CHANNEL_UPDATE_CLIENT_RUNS=pub_sub_channel_update_client_runs
  - PUBSUB_CHANNEL_CLIENT_ALERTS=pub_sub_channel_client_alerts
  - QUEUE_NAME_SEND_MAIL=notify_service_send_mail_queue
  - PUBSUB_CHANNEL_NOTIFICATIONS_SENT=pub_sub_channel_notifications_sent
  - PUBSUB_CHANNEL_EMAILS_SENT=pub_sub_channel_emails_sent

  ##############################
  #
  #  Ruby GC
  #
  ##############################
  - MALLOC_ARENA_MAX=3
  - RUBY_GC_HEAP_FREE_SLOTS=4096
  - RUBY_GC_HEAP_INIT_SLOTS=10000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.2
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=3096
  - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.2
  - RUBY_GC_MALLOC_LIMIT=8500000
  - RUBY_GC_MALLOC_LIMIT_MAX=15000000
  - RUBY_GC_MALLOC_LIMIT_GROWTH_FACTOR=1.2

  ##############################
  #
  #  Misc
  #
  ##############################
  - DISABLE_SPRING=1
  - SKIP_SIMPLECOV=true
  - WB_BILLING_SERVICE_CONFIRM_PAYOUT_EMAIL_LINK=https://waybetterdev.com/payout/confirm-email

services:
  #  daemons:
  #    memory: 512
  #    #command: "bash -c \"while [ true ]; do echo 'hi'; sleep 5; done\""
  #    command: ./bin/start_daemons.sh

  web:
    domain: ${WB_BILLING_SERVICE_DOMAIN}
    #command: "bash -c \"while [ true ]; do echo 'hi'; sleep 5; done\""
    command: bash -c 'wget https://dev.dietbet.com/files/convox/office-dev-convox-local-rack.crt -O "/usr/share/ca-certificates/convox.crt" && echo "convox.crt" >> "/etc/ca-certificates.conf" && update-ca-certificates && cat "/usr/share/ca-certificates/convox.crt" && export NODE_EXTRA_CA_CERTS="/usr/share/ca-certificates/convox.crt" && ./bin/start_web_server.sh'
    health:
      grace: 15
      path: /ping/lb
      interval: 60
      timeout: 3
    port: 3006
    memory: 512

