
environment:
  - GEN2=true
  - NPM_CONFIG_REGISTRY
services:
  web:
    domain: ${WB_GRAPHQL_SERVICE_DOMAIN}
    command: bash -c 'wget https://dev.dietbet.com/files/convox/ninja-selfsigned-rootCA.crt -O "/usr/share/ca-certificates/ninja-selfsigned-rootCA.crt" && export NODE_EXTRA_CA_CERTS="/usr/share/ca-certificates/ninja-selfsigned-rootCA.crt" && echo "ninja-selfsigned-rootCA.crt" >> "/etc/ca-certificates.conf" && cat "/usr/share/ca-certificates/ninja-selfsigned-rootCA.crt" && wget https://dev.dietbet.com/files/convox/office-selfsigned-rootCA.crt -O "/usr/share/ca-certificates/office-selfsigned-rootCA.crt" && export NODE_EXTRA_CA_CERTS="/usr/share/ca-certificates/office-selfsigned-rootCA.crt" && echo "office-selfsigned-rootCA.crt" >> "/etc/ca-certificates.conf" && cat "/usr/share/ca-certificates/office-selfsigned-rootCA.crt" && update-ca-certificates && echo "188.244.27.49 wb-user-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 wb-billing-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 wb-metric-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 wb-notify-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 wb-social-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 web.dietbet-game-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 wb-membership-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 wb-user-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 falkor-game-service.convox.office" >> "/etc/hosts" && echo "188.244.27.49 accounts-office.waybetterdev.com/" >> "/etc/hosts" && npm start'
    memory: 512
    #command: "bash -c \"while [ true ]; do echo 'hi'; sleep 5; done\""
    port: 3003
    internal: true
    scale:
      memory: 512
      count: 1
    health:
      grace: 30
      path: /ping/lb
      interval: 60
      timeout: 3
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PORT=3003
      - SHIFT_PORT=2923 # also referenced in wb-admin-web
      - API_CLIENT_JWT_SECRET
      - DIETBET_GAME_SERVICE_HOST
      - DIETBET_GAME_SERVICE_PORT
      - DIETBET_LEGACY_REST_API_HOST
      - DIETBET_LEGACY_REST_API_PORT
      - FALKOR_GAME_SERVICE_REST_API_HOST
      - FALKOR_GAME_SERVICE_REST_API_PORT
      - OP_IMAGE_SERVICE_REST_API_URL
      - NODE_ENV
      - QUEUE_NAME_REQUEST_METRIC_SERVICE_RUNS_UPDATE
      - REDIS_HOST
      - RUNBET_GAME_SERVICE_REST_API_HOST
      - RUNBET_GAME_SERVICE_REST_API_PORT
      - STEPBET_GAME_SERVICE_HOST
      - STEPBET_GAME_SERVICE_PORT
      - STEPBET_LEGACY_REST_API_HOST
      - STEPBET_LEGACY_REST_API_PORT
      - STRAVA_PROFILE_URL_BASE
      - TEMPORARY_FILE_BASE_PATH
      - WB_ADMIN_JWT_COOKIE
      - WB_ADMIN_WEB_EXTERNAL_URL
      - WB_AUTH_SERVICE_EXTERNAL_URL
      - WB_BILLING_SERVICE_REST_API_HOST
      - WB_BILLING_SERVICE_REST_API_PORT
      - WB_ENABLE_GRAPHQL_INTROSPECTION
      - WB_ENFORCE_HTTPS
      - WB_ENV
      - WB_GRAPHQL_SERVICE_KOA_GRAPHQL_DEBUG
      - WB_GRAPHQL_SERVICE_LOG_LEVEL
      - WB_INTERNAL_URL_SCHEME
      - WB_JWT_COOKIE
      - WB_METRIC_SERVICE_REST_API_HOST
      - WB_METRIC_SERVICE_REST_API_PORT
      - WB_NOTIFY_SERVICE_REST_API_HOST
      - WB_NOTIFY_SERVICE_REST_API_PORT
      - WB_SOCIAL_SERVICE_REST_API_HOST
      - WB_SOCIAL_SERVICE_REST_API_PORT
      - WB_USER_SERVICE_HOST
      - WB_USER_SERVICE_PORT

