services:
  web:
    command: bash -c 'wget https://dev.dietbet.com/files/convox/office-dev-convox-local-rack.crt -O "/usr/share/ca-certificates/convox.crt" && echo "convox.crt" >> "/etc/ca-certificates.conf" && update-ca-certificates && cat "/usr/share/ca-certificates/convox.crt" && export NODE_EXTRA_CA_CERTS="/usr/share/ca-certificates/convox.crt" && npm start'
    port: 3000
    domain: ${WB_HUB_DOMAIN}
    health:
      grace: 30
      path: /ping/lb
      interval: 30
    environment:
      - PORT=3000
      - BIND_ADDRESS=0.0.0.0

      - AB_PARAM_NAME
      - APPLE_CLIENT_ID
      - ASSET_CACHE_MAX_AGE
      - BASE_CONTENTFUL_IMAGE_URL
      - BRANCH_DIETBET_APP_KEY
      - BRANCH_RUNBET_APP_KEY
      - BRANCH_STEPBET_APP_KEY
      - CDN_BASE_URL=
      - CLOUDINARY_CLOUD_NAME
      - CONTENTFUL_HOST
      - CONTENTFUL_SPACE_ID
      - CONTENTFUL_TOKEN
      - DEFAULT_DIETBET_OFFER
      - DEFAULT_STEPBET_OFFER
      - DIETBET_AF_SMART_BANNER_KEY=
      - DIETBET_GAME_SERVICE_HOST
      - ERROR_REPORTING_ENABLED
      - ERROR_REPORTING_HOSTS
      - FACEBOOK_CLIENT_ID
      - GOOGLE_TAG_MANAGER_AUTH
      - GOOGLE_TAG_MANAGER_ENV_ID
      - GOOGLE_TAG_MANAGER_ID
      - GRAPHQL_URL
      - LOG_GRAPHQL_QUERIES
      - MAILCHIMP_HOST
      - MAILCHIMP_ID
      - NPM_CONFIG_REGISTRY
      - OPTIMONK_ID
      - OP_DEFAULT_GAME_IMAGES
      - OP_USER_GAME_IMAGES
      - OP_USER_WIDE_GAME_IMAGES
      - PAGE_CACHE_MAX_AGE
      - PAGE_CACHE_ENABLE
      - RECAPTCHA_SITE_KEY
      - REDIS_CACHE_KEY_PAGES
      - REDIS_CACHE_KEY_PAGE_FETCH_TIME
      - REDIS_CACHE_KEY_TEMPLATE
      - REDIS_CACHE_KEY_TEMPLATE_FETCH_TIME
      - REDIS_CACHE_PAGES_TIMEOUT
      - REDIS_HOST
      - REDIS_PAGES_HARD_CACHE_TIMEOUT
      - ROLLBAR_ADMIN_TOKEN
      - ROLLBAR_TOKEN
      - SEGMENT_WRITE_KEY
      - SUPPORT_EMAIL
      - WB_AUTH_SERVICE_BASE_URL
      - WB_AUTH_SERVICE_SESSION_COOKIE
      - WB_ENFORCE_HTTPS
      - WB_ENV
      - WB_HUB_LOG_LEVEL
      - WB_JWT_COOKIE
      - ZENDESK_KEY
