environment:
  ####################
  #                  #
  # General Settings #
  #                  #
  ####################
  - ALLOW_UNCONFIGURED_SERVICES=false
  - INIT_AND_SEED=false
  - PORT=3005
  - PUBSUB_CHANNEL_CLIENT_ALERTS=pub_sub_channel_client_alerts
  - PUBSUB_CHANNEL_UPDATE_CLIENT_RUNS=pub_sub_channel_update_client_runs
  - REDIS_HOST
  - SKIP_SIMPLECOV=true
  - WAIT_FOR_REDIS
  - WB_ENV
  - WB_INTERNAL_URL_SCHEME=http
  - API_CLIENT_JWT_SECRET
  - DISABLE_SPRING=1
  - GEN2=true
  ###########################
  #                         #
  # Service to Service URLs #
  #                         #
  ###########################
  - RUNBET_GAME_SERVICE_HOST
  #####################
  #                   #
  # Database Settings #
  #                   #
  #####################
  - WB_SOCIAL_SERVICE_DB_HOST
  - WB_SOCIAL_SERVICE_DB_PASSWORD
  - WB_SOCIAL_SERVICE_DB_PORT
  - WB_SOCIAL_SERVICE_DB_USERNAME
  - WB_SOCIAL_SERVICE_WEB_CONCURRENCY
  - WB_SOCIAL_SERVICE_MAX_THREADS
  ################
  #              #
  # Gem Settings #
  #              #
  ################
  - GEMFURY_SECRET
  - WB_MESSAGING_GEM_PATH=
  - WB_SERVICE_GEM_PATH=
  - WEBSPRAY_GEM_PATH=
  - RACK_JWT_GEM_PATH=
  ####################
  #                  #
  # Ruby GC settings #
  #                  #
  ####################
  - MALLOC_ARENA_MAX=3 # default: none
  - RUBY_GC_HEAP_FREE_SLOTS=4096 # default 4096   Must be > 0
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.2 # default 1.8   Must be > 1.0
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=3096 # default 0 (disabled);Must be > 0
  - RUBY_GC_HEAP_INIT_SLOTS=10000 # default 10000  Must be > 0
  - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.2 # default 2.0   Must be > 0
  - RUBY_GC_MALLOC_LIMIT=8500000 # default 16777216  Must be > 0
  - RUBY_GC_MALLOC_LIMIT_GROWTH_FACTOR=1.2 # default 1.4   Must be > 1.0
  - RUBY_GC_MALLOC_LIMIT_MAX=15000000 # default 33554432   Must be > 0

services:
  web:
    #command: "bash -c \"while [ true ]; do echo 'hi'; sleep 5; done\""
    command: ./bin/start_web_server.sh
    health:
      path: /ping/lb
      interval: 60
      timeout: 3
    scale:
      memory: 512
    port: 3005
    internal: true
