environment:
  - GEN2=true
  - NPM_CONFIG_REGISTRY
services:
  web:
    internal: true
    command: bash -c 'wget https://dev.dietbet.com/files/convox/office-dev-convox-local-rack.crt -O "/usr/share/ca-certificates/convox.crt" && echo "convox.crt" >> "/etc/ca-certificates.conf" && update-ca-certificates && cat "/usr/share/ca-certificates/convox.crt" && export NODE_EXTRA_CA_CERTS="/usr/share/ca-certificates/convox.crt" && npm start'
    port: 4000
    scale:
      memory: 512
    health:
      path: /ping/lb
    environment:
      - PORT=4000
      - API_CLIENT_JWT_SECRET
      - ELIGIBLE_PRODUCTS_FOR_INTEREST=dietbet,stepbet,runbet,quitbet,waybetter
      - FACEBOOK_CLIENT_SECRET
      - FITBIT_CLIENT_ID
      - FITBIT_CLIENT_SECRET
      - FITBIT_ACTIVITIES_SUBSCRIPTION_ID
      - FITBIT_ACTIVITIES_SUBSCRIBER_ID
      - GARMIN_CLIENT_ID
      - GARMIN_CLIENT_SECRET
      - NPM_CONFIG_REGISTRY
      - NODE_ENV=development
      - REDIS_HOST
      - STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET
      - WAYBETTER_APPLE_CLIENT_KEY
      - WAYBETTER_APPLE_CLIENT_SECRET
      - WAYBETTER_APPLE_CLIENT_TEAM_ID
      - WB_ENV
      - WB_HEALTH_CHECK_USERNAME
      - WB_HEALTH_CHECK_PASSWORD
      - WB_INTERNAL_URL_SCHEME=http
      - WB_JWT_COOKIE
      # notify service convox G1 link
      - WB_NOTIFY_SERVICE_REST_API_HOST
      - WB_NOTIFY_SERVICE_REST_API_PORT
      - WB_NOTIFY_SERVICE_REST_API_ENABLED=true
      - WB_USER_SERVICE_FORGOT_PASSWORD_EXPIRES_HOURS
      - WB_USER_SERVICE_HUB_FORGOT_PASSWORD_LINK
      - WB_USER_SERVICE_LOG_LEVEL=info
      # db/config.js
      - WB_USER_DB_POOL_MAX=5
      - WB_USER_DB_POOL_MIN=0
      - WB_USER_DB_HOST
      - WB_USER_DB_USERNAME
      - WB_USER_DB_PASSWORD
      # package.json script
      - WB_USER_SERVICE_NODEMON_EXEC
