


AllCops:
  Exclude:
    - 'kmd-local'
    - 'krubocop'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/InterpolationCheck:
  Enabled: false