#!/usr/bin/env ruby
# frozen_string_literal: true

require File.expand_path(__dir__) + '/includes/op_base.rb'

class RunService < OpBase
  attr_accessor :opts_exec
  
  def go
    parse_opts

    if opts_exec
      opts_np_app.run_command(opts_exec)
    else
      opts_np_app.run_connect_command
    end

  end

  HELP = <<-BAN
  Execute commands either on local rails and node apps with all ENV variables preloaded.
  Ex:
    np-service-run -a wb-user-service
  BAN

  def parse_opts
    self.option_parser = OptionParser.new do |opts|
      opts.banner = HELP

      opts.separator ''
      opts.separator 'Specific options:'

      add_debug_option(opts)
      add_exec_option(opts)

      add_np_app_option(opts)

      add_help_option(opts)
    end
    option_parser.parse!(ARGV)

    exit_with_error('app parameter is required') if opts_np_app_name.nil?
  end

  def add_exec_option(opts)
    opts.on('-e', '--exec=e', 'Command to execute') do |x|
      self.opts_exec = x
    end
  end

end

RunService.new.go
