#!/usr/bin/env ruby

public

require 'optparse'
require 'open3'

begin
  require 'highline'
  require 'colored'
  require 'terminfo'
rescue LoadError => x
  puts <<-XXX
To run this utility:
  gem install 'highline'
  gem install 'colored'
  gem install 'ruby-terminfo'
XXX
  exit(1)
end

require File.expand_path('../', __FILE__) + "/includes/op-base.rb"

# CLI script which will start tmux
class ReloadYml < OpBase
  def go
    app = File.basename(Dir.getwd)

    unless np_service_location(app) == 'convox-local'
      warn "Error: app '".red + app.to_s.green + "' is not on local convox".red
      exit 1
    end
    
    exec_ic_command "kmd-local refresh-yml -- local #{app}"
  end
end

ReloadYml.new.go