#!/usr/bin/env ruby

public

require 'optparse'
require 'open3'

begin
  require 'highline'
  require 'colored'
  require 'terminfo'
rescue LoadError => x
  puts <<-XXX
To run this utility:
  gem install 'highline'
  gem install 'colored'
  gem install 'ruby-terminfo'
XXX
  exit(1)
end

require File.expand_path('../', __FILE__) + "/includes/op-base.rb"

# CLI script which will start tmux
class ReloadEnv < OpBase
  def go
    app = File.basename(Dir.getwd)

    unless np_service_is_on_local_convox(app)
      warn "Error: app '".red + app.to_s.green + "' is not on local convox".red
      exit 1
    end
    
    exec_ic_command "env-builder -w -a #{app}"
    exec_ic_command "kmd-local refresh-env -- local #{app} no-confirm"
  end
end

ReloadEnv.new.go