#!/usr/bin/env ruby
# frozen_string_literal: true

require File.expand_path(__dir__) + '/includes/op_base.rb'
require File.expand_path(__dir__) + '/includes/kenv.rb'

class RunService < OpBase
  attr_accessor :opts_np_app

  ENV_OVERRIDES = {
    'WB_LOCAL_STANDALONE' => 'true',
    'RAILS_ENV' => 'development',
    'WB_NOTIFY_SERVICE_DAEMON_THREADS' => '1',
    'WB_NOTIFY_SERVICE_MAX_HTTP_THREADS' => '1'
  }.freeze

  def go
    parse_opts

    Kenv.exec_with_env(
      app: File.basename(np_service_path(opts_np_app)),
      service: 'web',
      args: [opts_exec],
      extra_env: ENV_OVERRIDES,
      global_env_fn: np_service_env_path(opts_np_app)
    )
  end

  HELP = <<-BAN
  Execute commands either on local rails and node apps with all ENV variables preloaded.
  Ex:
    prepare-node-app -a wb-user-service
  BAN

  def parse_opts
    self.option_parser = OptionParser.new do |opts|
      opts.banner = HELP

      opts.separator ''
      opts.separator 'Specific options:'

      add_debug_option(opts)
      add_exec_option(opts)

      add_np_app_option(opts)

      add_help_option(opts)
    end
    option_parser.parse!(ARGV)

    exit_with_error('app parameter is required') if opts_np_app.nil?
  end
end

RunService.new.go
